services:
  mysb:
    container_name: mysb
    image: mysb:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
    environment:
      - APPLICATION_NAME=lab3
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=lab3db
      - DB_USER=boarduser
      - DB_PASSWORD=boardpass
      - KAFKA_URL=kafka:9092
    volumes:
      - board-data:/var/lib/test/data
    networks: [ microservices ]

  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lab3db
      POSTGRES_USER: boarduser
      POSTGRES_PASSWORD: boardpass
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: [ microservices ]

  kafka:
    container_name: kafka
    image: apache/kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=INTERNAL://:9091,EXTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9091,EXTERNAL://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_RETENTION_BYTES=2147483648
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks: [ microservices ]

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - "kafka"
    networks: [ microservices ]

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks: [ microservices ]

volumes:
  db-data:
  board-data:
  pgadmin-data:
  kafka-data:

networks:
  microservices:
    driver: bridge