services:
  bot:
    container_name: scalaTgBot
    image: scala/bot:latest
    build:
      context: .
      dockerfile: DockerfileComplexBuild
    ports:
      - "8081:8081"
#    environment:
#      - BOT_API_TOKEN={token}