name: DockerComposeCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build containers
        run: |
          cd lab4r
          docker compose build

      - name: Start containers
        run: |
          cd lab4r
          docker compose up -d

      - name: Wait for services to be ready
        run: |
          cd lab4r
          sleep 10
          docker compose ps

      - name: Show logs on failure
        if: failure()
        run: |
          cd lab4r
          docker compose  logs

      - name: Stop containers
        if: always()
        run: |
          cd lab4r
          docker compose down